// Datos del catálogo GOLD CLOTHES
const PRODUCTS = [
  {id:1, name:"Buzo Normal Cuello Redondo", category:"Buzos y Sudaderas", colors:["Rojo", "Verde", "Morado Lila", "Negro", "Gris", "Blanco", "Azul oscuro", "Beige"], price:45000, img:"productos/Buzo Cuello Redondo.png"},
  {id:2, name:"Corset ajustable", category:"Bodies y Corsets", colors:["Lila", "Blanco"], price:30000, img:"productos/Corset ajustable.png"},
  {id:3, name:"Buzo Oversize", category:"Buzos y Sudaderas", colors:["Negro", "Gris", "Rojo", "Azul", "Morado", "Verde", "Cafe"], price:65000, img:"productos/Buzo Corto Mujer Oversize.png"},
  {id:4, name:"Camiseta Multimarca", category:"Camisetas y Camisas", colors:["Rojo", "Beige", "Rosado", "Verde", "Amarillo", "Azul", "Blanco", "Gris", "Negro"], price:35000, img:"productos/Camiseta Multimarca.png"},
  {id:5, name:"Blusa Polo Mujer", category:"Blusas y Tops", colors:["Vinotinto", "Roja", "Azul cielo"], price:27000, img:"productos/Blusa Polo Mujer.png"},
  {id:6, name:"Corset Encaje", category:"Bodies y Corsets", colors:["Negro", "Rosado", "Blanco", "Amarillo"], price:45000, img:"productos/Corset Encaje.png"},
  {id:7, name:"Body Malla", category:"Bodies y Corsets", colors:[], price:40000, img:"productos/Body malla Mangas.png"},
  {id:8, name:"Short Liso", category:"Shorts", colors:["Rojo", "Negro", "Azul", "Gris", "Verde", "Rosado", "Morado"], price:25000, img:"productos/Short Liso.png"},
  {id:9, name:"Licra Lisa", category:"Licras", colors:["Gris", "Azul", "Rojo", "Verde", "Negro"], price:35000, img:"productos/Licra Lisa.png"},
  {id:10, name:"Short acanalado", category:"Shorts", colors:["Rosado"], price:30000, img:"productos/Enterizo Short Acanalado.png"},
  {id:11, name:"Medias", category:"Accesorios", colors:[], price:12000, img:"productos/Medias.png"},
  {id:12, name:"Top Deportivo", category:"Blusas y Tops", colors:["Blanco", "Azul", "Gris"], price:35000, img:"productos/Top Deportivo.png"},
  {id:13, name:"Vestido apertura espalda", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/Vestido apertura espalda.png"},
  {id:14, name:"Enterizo suplex", category:"Conjuntos y Enteriozos", colors:["Negro", "Rojo"], price:60000, img:"productos/Enterizo suplex.png"},
  {id:15, name:"Pantaloneta Mujer con Licra", category:"Licras", colors:["Gris", "Blanca"], price:50000, img:"productos/Pantaloneta Mujer con Licra.png"},
  {id:16, name:"Buzo Deportivo Hombre", category:"Buzos y Sudaderas", colors:["Gris"], price:60000, img:"productos/Buzo Deportivo Hombre.png"},
  {id:17, name:"Enterizo Bota Entubada", category:"Conjuntos y Enteriozos", colors:["Beige", "Negro", "Blanco", "Rojo"], price:65000, img:"productos/Enterizo Bota Entubada.png"},
  {id:18, name:"Blusa Esqueleto Líneas", category:"Blusas y Tops", colors:["Rosada"], price:27000, img:"productos/Blusa Esqueleto Líneas.png"},
  {id:19, name:"Blusa Adidas Corta", category:"Blusas y Tops", colors:["Lila", "Azul cielo"], price:30000, img:"productos/Blusa Adidas Corta.png"},
  {id:20, name:"Vestido Polo Largo", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:45000, img:"productos/Vestido Polo Largo.png"},
  {id:21, name:"Vestido Polo Corto", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:42000, img:"productos/Vestido Polo Corto.png"},
  {id:22, name:"Enterizo Short Acanalado", category:"Conjuntos y Enteriozos", colors:["Rosado", "Beige", "Rosado"], price:42000, img:"productos/Enterizo con Copas Acanalado.png"},
  {id:23, name:"Vestido Aro", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/Vestido Aro.png"},
  {id:24, name:"Vestido Mariposa", category:"Vestidos", colors:["Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/Vestido Mariposa.png"},
  {id:25, name:"Buzo Licra Deportivo", category:"Buzos y Sudaderas", colors:["Rojo", "Negro", "Gris", "Verde", "Azul"], price:40000, img:"productos/Buzo Licra Deportivo.png"},
  {id:26, name:"Conjunto Deportivo", category:"Conjuntos y Enteriozos", colors:["Rojo", "Negro", "Azul", "Gris", "Vinotinto"], price:55000, img:"productos/Conjunto Deportivo 2 Piezas.png"},
  {id:27, name:"Vestido Cuello Bandeja Doble", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:60000, img:"productos/Vestido Cuello Bandeja Doble.png"},
  {id:28, name:"Buzo Utopía Unisex", category:"Buzos y Sudaderas", colors:["Blanco", "Rojo", "Gris", "Azul oscuro", "Negro", "Verde", "Amarillo"], price:70000, img:"productos/Hoodie Cremallera.png"},
  {id:29, name:"Licra Importada en V", category:"Licras", colors:["Verde"], price:48000, img:"productos/Licra Importada en V.png"},
  {id:30, name:"Corset Malla", category:"Bodies y Corsets", colors:["Rojo", "Blanco Negro", "Camel"], price:40000, img:"productos/Corset Malla.png"},
  {id:31, name:"Camiseta oversize basica", category:"Blusas y Tops", colors:["Blanca", "Azul", "Negra", "Roja", "Vinotinto", "Amarilla"], price:25000, img:"productos/Camiseta oversize basica.png"},
  {id:32, name:"Blusa Mariposa", category:"Blusas y Tops", colors:["Blanca", "Negra", "Marfil"], price:35000, img:"productos/Blusa Mariposa.png"},
  {id:33, name:"Enterizo Súplex Corto", category:"Conjuntos y Enteriozos", colors:["Negro", "Azul"], price:45000, img:"productos/Enterizo Súplex Corto.png"},
  {id:34, name:"Falda Short deportiva", category:"Shorts", colors:["Negro", "Azul", "Morada", "Gris", "Vinotinto"], price:35000, img:"productos/Falda Short deportiva.png"},
  {id:35, name:"Buzo Corto Mujer Oversize", category:"Buzos y Sudaderas", colors:["Blanco", "Rojo", "Azul", "Verde", "Lila", "Negro"], price:40000, img:"productos/Buzo Oversize.png"},
  {id:36, name:"Licra Push-up Huecos", category:"Licras", colors:["Azul oscuro"], price:45000, img:"productos/Licra Push-up Huecos.png"},
  {id:37, name:"Conjunto Manchado Top", category:"Conjuntos y Enteriozos", colors:["Azul oscuro", "Morado", "Verde", "Negro"], price:65000, img:"productos/Conjunto Manchado Top.PNG"},
  {id:38, name:"Jeans Skinny", category:"Pantalones y Jeans", colors:["Negro", "Azul", "Gris oscuro", "Azul claro"], price:65000, img:"productos/Jeans Skinny.png"},
  {id:39, name:"Corset con mangas", category:"Bodies y Corsets", colors:["Blanco"], price:50000, img:"productos/Corset con mangas.png"},
  {id:40, name:"Blusa con Mangas Malla", category:"Blusas y Tops", colors:["Blanca", "Negra", "Cafe", "Roja"], price:40000, img:"productos/Blusa con Mangas Malla.png"},
  {id:41, name:"Top Básico Malla", category:"Blusas y Tops", colors:["Blanco", "Negro", "Roja", "Marfil"], price:30000, img:"productos/Top Básico Malla.png"},
  {id:42, name:"Body malla Mangas", category:"Bodies y Corsets", colors:["Blanco", "Negro", "Rojo", "Aziul", "Amarillo"], price:35000, img:"productos/Body Malla.png"},
  {id:43, name:"Buzo Utopía Cremallera", category:"Buzos y Sudaderas", colors:["Verde", "Lila", "Negro", "Azul", "Rojo", "Amarillo", "Blanco", "Gris"], price:70000, img:"productos/Hoodie.png"},
  {id:44, name:"Vestido con Correa", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/Vestido con Correa.png"},
  {id:45, name:"Vestido Animal Print", category:"Vestidos", colors:[], price:60000, img:"productos/Vestido Animal Print.png"},
  {id:46, name:"Jean Ancho Básico", category:"Pantalones y Jeans", colors:["Negro", "Azul"], price:85000, img:"productos/Jean Ancho Básico.png"},
  {id:47, name:"Jean Pedrería", category:"Pantalones y Jeans", colors:[], price:110000, img:"productos/Jean Pedrería.png"},
  {id:48, name:"Jean Ancho Rasgado", category:"Pantalones y Jeans", colors:[], price:100000, img:"productos/Jean Ancho Rasgado.png"},
  {id:49, name:"Vestido Paris", category:"Vestidos", colors:["Camel", "Negro", "Azul cielo", "Lila", "Rojo", "Blanco"], price:50000, img:"productos/Vestido Paris.PNG"},
  {id:50, name:"Vestido Malla", category:"Vestidos", colors:["Rojo", "Blanco", "Negro"], price:60000, img:"productos/Vestido Malla.PNG"},
  {id:51, name:"Vestido Campesina", category:"Vestidos", colors:["Rojo", "Azul cielo", "Lila", "Beige", "Blanco", "Negro"], price:50000, img:"productos/Vestido Campesina.PNG"},
  {id:52, name:"Corset Corazón", category:"Bodies y Corsets", colors:["Beige", "Rojo", "Negro"], price:40000, img:"productos/Corset Corazón.png"},
  {id:53, name:"Crop Mariposa", category:"Blusas y Tops", colors:["Blanco", "Rojo", "Negra"], price:45000, img:"productos/Crop Mariposa.png"},
  {id:54, name:"Body Melissa", category:"Bodies y Corsets", colors:["Beige", "Azul oscuro", "Rojo", "Blanco", "Vinotinto"], price:45000, img:"productos/Body Melissa.png"},
  {id:55, name:"Body Encaje", category:"Bodies y Corsets", colors:["Blanco"], price:45000, img:"productos/Body Encaje.png"},
  {id:56, name:"Camisa Oversize Líneas", category:"Camisetas y Camisas", colors:["Verde", "Negro", "Blanco", "Azul", "Rojo"], price:60000, img:"productos/Camisa Oversize Líneas.png"},
  {id:57, name:"Blusa Tela Galleta", category:"Blusas y Tops", colors:["Blanco", "Negro"], price:28000, img:"productos/Blusa Tela Galleta.png"},
  {id:58, name:"Body W Liciado", category:"Bodies y Corsets", colors:["Rojo", "Negro", "Beige", "Blanco", "Azul oscuro"], price:45000, img:"productos/Body W Liciado.png"},
  {id:59, name:"Short Biker", category:"Shorts", colors:["Rojo", "Azul", "Gris", "Negro", "Lila", "Rosado", "Morado", "Verde"], price:30000, img:"productos/Short Biker.PNG"},
  {id:60, name:"Camisa Licrada Nacional", category:"Camisetas y Camisas", colors:["Gris", "Verde", "Negra", "Azul"], price:35000, img:"productos/Camisa Licrada Nacional.png"},
  {id:61, name:"Camisa Sport Importada", category:"Camisetas y Camisas", colors:["Blanca", "Azul", "Roja", "Negra", "Verde", "Gris"], price:45000, img:"productos/Camisa Sport Importada.png"},
  {id:62, name:"Enterizo Adidas", category:"Conjuntos y Enteriozos", colors:["Beige"], price:65000, img:"productos/Enterizo Adidas.png"},
  {id:63, name:"Sudadera Oversize Hombre", category:"Buzos y Sudaderas", colors:["Morada", "Verde", "Rojo", "Negra", "Blanca"], price:60000, img:"productos/Sudadera Oversize Hombre.png"},
  {id:64, name:"Body Escote Espalda", category:"Bodies y Corsets", colors:["Azul", "Amarillo", "Negro", "Blanco", "Vinotinto", "Rosado"], price:60000, img:"productos/Body Escote Espalda.png"},
  {id:65, name:"Blusa Triángulo", category:"Blusas y Tops", colors:["Negra", "Blanca", "Azul cielo", "Amarilla", "Rosado"], price:60000, img:"productos/Blusa Triángulo.png"},
  {id:66, name:"Blusa Elegante", category:"Blusas y Tops", colors:["Amarillo", "Negro", "Blanco", "Azul cielo", "Rosado", "Vinotinto"], price:40000, img:"productos/Blusa Elegante Malla.png"},
  {id:67, name:"Body Elegante", category:"Bodies y Corsets", colors:["Rojo", "Negro", "Beige"], price:60000, img:"productos/Body Elegante.png"},
  {id:68, name:"Camisa Oversize Galleta", category:"Camisetas y Camisas", colors:["Negro", "Marfil", "Beige"], price:55000, img:"productos/Camisa Oversize Galleta.png"},
  {id:69, name:"Falda Short Cuero", category:"Shorts", colors:["Vinotinto", "Café", "Negro", "Beige"], price:50000, img:"productos/Falda Short Cuero.png"},
  {id:70, name:"Falda Cuero", category:"Faldas", colors:["Cafe", "Negro", "Vinotinto", "Beige"], price:45000, img:"productos/Falda Cuero Larga.png"},
  {id:71, name:"Falda Cuero Larga", category:"Faldas", colors:["Negro", "Beige", "Vinotinto", "Cafe"], price:55000, img:"productos/Falda Cuero.png"},
  {id:72, name:"Enterizo con Copas Acanalado", category:"Conjuntos y Enteriozos", colors:["Azul Cielo"], price:90000, img:"productos/Enterizo Corto Apertura Espalda.png"},
  {id:73, name:"Chaqueta Corta Deportiva", category:"Chaquetas", colors:["Roja", "Lila", "Gris", "Negra"], price:40000, img:"productos/Chaqueta Corta Deportiva.png"},
  {id:74, name:"Vestido Straple", category:"Vestidos", colors:["Negro", "Rojo", "Camel", "Azul"], price:50000, img:"productos/Vestido Straple.PNG"},
  {id:75, name:"Vestido Prenses", category:"Vestidos", colors:["Azul cielo", "Negro", "Cafe"], price:50000, img:"productos/Falda de Dril Prenses.png"},
  {id:76, name:"Body Straple", category:"Bodies y Corsets", colors:["Amarillo", "Gris", "Negro"], price:40000, img:"productos/Body Straple.png"},
  {id:77, name:"Blusa Elegante Malla", category:"Blusas y Tops", colors:["Negra", "Azul Cielo"], price:35000, img:"productos/Blusa Elegante.png"},
  {id:78, name:"Conjunto Polo", category:"Conjuntos y Enteriozos", colors:["Negro", "Camel", "Rojo", "Azul cielo", "Blanco", "Rosado"], price:70000, img:"productos/Conjunto Polo.png"},
  {id:79, name:"Vestido Bandeja Abertura", category:"Vestidos", colors:["Verde manzana", "Rojo", "Negro"], price:50000, img:"productos/Vestido Bandeja Abertura.png"},
  {id:80, name:"Blusa Bandeja Larga", category:"Blusas y Tops", colors:["Negro"], price:50000, img:"productos/Blusa Bandeja Larga.png"},
  {id:81, name:"Esqueleto Malla", category:"Bodies y Corsets", colors:["Azul cielo", "Rosado", "Amarillo", "Vinotinto"], price:40000, img:"productos/Esqueleto Malla.png"},
  {id:82, name:"Falda de Dril Prenses", category:"Faldas", colors:["Negro", "Beige", "Azul cielo"], price:45000, img:"productos/Falda de Dril Prenses.png"},
  {id:83, name:"Blusa Bandeja corta", category:"Buzos y Sudaderas", colors:["Negro", "Vinotinto"], price:40000, img:"productos/Blusa Bandeja corta.png"},
  {id:84, name:"Pantalón Algodón", category:"Pantalones y Jeans", colors:["Gris claro", "Negro", "Rojo", "Cafe"], price:45000, img:"productos/Pantalón Algodón.png"},
  {id:85, name:"Pantalón Pana", category:"Pantalones y Jeans", colors:["Rosado", "Negro", "Marfil"], price:45000, img:"productos/Pantalón Pana.png"},
  {id:86, name:"Pantalón Polo dama", category:"Pantalones y Jeans", colors:["Cafe"], price:40000, img:"productos/Pantalón Polo dama.png"},
  {id:87, name:"Pantalón Hombre Joger", category:"Pantalones y Jeans", colors:["Negro", "Gris", "Gris raton"], price:40000, img:"productos/Pantalón Hombre Joger.png"},
  {id:88, name:"Licra Push-up", category:"Licras", colors:["Gris", "Azul oscuro", "Verde", "Morada"], price:45000, img:"productos/Licra Push-up.png"},
  {id:89, name:"Short Push-up Manchas", category:"Shorts", colors:["Azul cielo", "Rojo", "Negro", "Morado"], price:38000, img:"productos/Short Push-up Manchas.png"},
  {id:90, name:"Conjunto Deportivo 2 Piezas", category:"Conjuntos y Enteriozos", colors:["Verde", "Negro"], price:100000, img:"productos/Conjunto Deportivo.png"},
  {id:91, name:"Enterizo Corto Apertura Espalda", category:"Conjuntos y Enteriozos", colors:["Vinotinto", "Oscuro", "Verde"], price:65000, img:"productos/Enterizo Corto Apertura Espalda.png"},
  {id:92, name:"Camiseta Polo", category:"Camisetas y Camisas", colors:["Azul cielo", "Azul oscuro", "Oscuro"], price:45000, img:"productos/Camiseta Polo Línea.png"},
  {id:93, name:"Camiseta Polo Línea", category:"Camisetas y Camisas", colors:["Rojo", "Azul oscuro"], price:50000, img:"productos/Camiseta Polo.png"},
  {id:94, name:"Gorras Planas Beisboleras", category:"Accesorios", colors:[], price:55000, img:"productos/Gorras Planas Beisboleras Cerradas.png"},
  {id:95, name:"Gorras Planas Beisboleras Cerradas", category:"Accesorios", colors:[], price:60000, img:"productos/Gorras Planas Beisboleras.png"},
  {id:96, name:"Gorras Planas Multimarca", category:"Accesorios", colors:[], price:50000, img:"productos/Gorras Planas Multimarca.png"},
  {id:97, name:"Gorras Curvas Beisboleras", category:"Accesorios", colors:[], price:50000, img:"productos/Gorras Curvas Beisboleras.png"},
  {id:98, name:"Gorras Multimarca 1.1", category:"Accesorios", colors:[], price:50000, img:"productos/Gorras Multimarca 1.1.PNG"},
  {id:99, name:"Gorras Multimarca", category:"Accesorios", colors:[], price:45000, img:"productos/Gorra Multimarca.png"},
];

const CATEGORIES = [...new Set(PRODUCTS.map(p => p.category))].sort();
