// Datos del catálogo GOLD CLOTHES — generado desde gold-clothes-catalog.json
// Para poner las fotos reales: sube cada imagen a la carpeta /productos/ con el
// nombre exacto indicado en el campo "img" de cada producto (ej: productos/001.jpg)
const STORE = {"name":"Gold Clothes","currency":"COP"};

const PRODUCTS = [
  {id:1, name:"Buzo Cuello Redondo", category:"Buzos y Sudaderas", colors:["Rojo", "Verde", "Morado Lila", "Negro", "Gris", "Blanco", "Azul oscuro", "Beige"], price:45000, img:"productos/001.jpg"},
  {id:2, name:"Corset ajustable", category:"Bodies y Corsets", colors:["Lila", "Blanco"], price:30000, img:"productos/002.jpg"},
  {id:3, name:"Buzo Oversize", category:"Buzos y Sudaderas", colors:["Negro", "Gris", "Rojo", "Azul", "Morado", "Verde", "Cafe"], price:65000, img:"productos/035.jpg"},
  {id:4, name:"Camiseta Multimarca", category:"Camisetas y Camisas", colors:["Rojo", "Beige", "Rosado", "Verde", "Amarillo", "Azul", "Blanco", "Gris", "Negro"], price:35000, img:"productos/004.jpg"},
  {id:5, name:"Blusa Polo Mujer", category:"Blusas y Tops", colors:["Vinotinto", "Roja", "Azul cielo"], price:27000, img:"productos/005.jpg"},
  {id:6, name:"Corset Encaje", category:"Bodies y Corsets", colors:["Negro", "Rosado", "Blanco", "Amarillo"], price:45000, img:"productos/006.jpg"},
  {id:7, name:"Body Malla", category:"Bodies y Corsets", colors:[], price:40000, img:"productos/007.jpg"},
  {id:8, name:"Short Liso", category:"Shorts", colors:["Rojo", "Negro", "Azul", "Gris", "Verde", "Rosado", "Morado"], price:25000, img:"productos/008.jpg"},
  {id:9, name:"Licra Lisa", category:"Licras", colors:["Gris", "Azul", "Rojo", "Verde", "Negro"], price:35000, img:"productos/009.jpg"},
  {id:10, name:"Short acanalado", category:"Shorts", colors:["Rosado"], price:30000, img:"productos/010.jpg"},
  {id:11, name:"Medias", category:"Accesorios", colors:[], price:12000, img:"productos/011.jpg"},
  {id:12, name:"Top Deportivo", category:"Blusas y Tops", colors:["Blanco", "Azul", "Gris"], price:35000, img:"productos/012.jpg"},
  {id:13, name:"Vestido apertura espalda", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/013.jpg"},
  {id:14, name:"Enterizo suplex", category:"Conjuntos y Enteriozos", colors:["Negro", "Rojo"], price:60000, img:"productos/014.jpg"},
  {id:15, name:"Pantaloneta Mujer con Licra", category:"Licras", colors:["Gris", "Blanca"], price:50000, img:"productos/015.jpg"},
  {id:16, name:"Buzo Deportivo Hombre", category:"Buzos y Sudaderas", colors:["Gris"], price:60000, img:"productos/016.jpg"},
  {id:17, name:"Enterizo Bota Entubada", category:"Conjuntos y Enteriozos", colors:["Beige", "Negro", "Blanco", "Rojo"], price:65000, img:"productos/017.jpg"},
  {id:18, name:"Blusa Esqueleto Líneas", category:"Blusas y Tops", colors:["Rosada"], price:27000, img:"productos/018.jpg"},
  {id:19, name:"Blusa Adidas Corta", category:"Blusas y Tops", colors:["Lila", "Azul cielo"], price:30000, img:"productos/019.jpg"},
  {id:20, name:"Vestido Polo Largo", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:45000, img:"productos/020.jpg"},
  {id:21, name:"Vestido Polo Corto", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:42000, img:"productos/021.jpg"},
  {id:22, name:"Enterizo Short Acanalado", category:"Conjuntos y Enteriozos", colors:["Rosado", "Beige", "Rosado"], price:42000, img:"productos/022.jpg"},
  {id:23, name:"Vestido Aro", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/023.jpg"},
  {id:24, name:"Vestido Mariposa", category:"Vestidos", colors:["Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/024.jpg"},
  {id:25, name:"Buzo Licra Deportivo", category:"Buzos y Sudaderas", colors:["Rojo", "Negro", "Gris", "Verde", "Azul"], price:40000, img:"productos/025.jpg"},
  {id:26, name:"Conjunto Deportivo", category:"Conjuntos y Enteriozos", colors:["Rojo", "Negro", "Azul", "Gris", "Vinotinto"], price:55000, img:"productos/026.jpg"},
  {id:27, name:"Vestido Cuello Bandeja Doble", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:60000, img:"productos/027.jpg"},
  {id:28, name:"Hoodie", category:"Buzos y Sudaderas", colors:["Blanco", "Rojo", "Gris", "Azul oscuro", "Negro", "Verde", "Amarillo"], price:70000, img:"productos/028.jpg"},
  {id:29, name:"Licra Importada en V", category:"Licras", colors:["Verde"], price:48000, img:"productos/029.jpg"},
  {id:30, name:"Corset Malla", category:"Bodies y Corsets", colors:["Rojo", "Blanco Negro", "Camel"], price:40000, img:"productos/030.jpg"},
  {id:31, name:"Camiseta oversize basica", category:"Blusas y Tops", colors:["Blanca", "Azul", "Negra", "Roja", "Vinotinto", "Amarilla"], price:25000, img:"productos/031.jpg"},
  {id:32, name:"Blusa Mariposa", category:"Blusas y Tops", colors:["Blanca", "Negra", "Marfil"], price:35000, img:"productos/032.jpg"},
  {id:33, name:"Enterizo Súplex Corto", category:"Conjuntos y Enteriozos", colors:["Negro", "Azul"], price:45000, img:"productos/033.jpg"},
  {id:34, name:"Falda Short deportiva", category:"Shorts", colors:["Negro", "Azul", "Morada", "Gris", "Vinotinto"], price:35000, img:"productos/034.jpg"},
  {id:35, name:"Buzo Corto Mujer Oversize", category:"Buzos y Sudaderas", colors:["Blanco", "Rojo", "Azul", "Verde", "Lila", "Negro"], price:40000, img:"productos/003.jpg"},
  {id:36, name:"Licra Push-up Huecos", category:"Licras", colors:["Azul oscuro"], price:45000, img:"productos/036.jpg"},
  {id:37, name:"Conjunto Manchado Top", category:"Conjuntos y Enteriozos", colors:["Azul oscuro", "Morado", "Verde", "Negro"], price:65000, img:"productos/037.jpg"},
  {id:38, name:"Jeans Skinny", category:"Pantalones y Jeans", colors:["Negro", "Azul", "Gris oscuro", "Azul claro"], price:65000, img:"productos/038.jpg"},
  {id:39, name:"Corset con mangas", category:"Bodies y Corsets", colors:["Blanco"], price:50000, img:"productos/039.jpg"},
  {id:40, name:"Blusa con Mangas Malla", category:"Blusas y Tops", colors:["Blanca", "Negra", "Cafe", "Roja"], price:40000, img:"productos/040.jpg"},
  {id:41, name:"Top Básico Malla", category:"Blusas y Tops", colors:["Blanco", "Negro", "Roja", "Marfil"], price:30000, img:"productos/041.jpg"},
  {id:42, name:"Body malla Mangas", category:"Bodies y Corsets", colors:["Blanco", "Negro", "Rojo", "Aziul", "Amarillo"], price:35000, img:"productos/042.jpg"},
  {id:43, name:"Hoodie Cremallera", category:"Buzos y Sudaderas", colors:["Verde", "Lila", "Negro", "Azul", "Rojo", "Amarillo", "Blanco", "Gris"], price:70000, img:"productos/043.jpg"},
  {id:44, name:"Vestido con Correa", category:"Vestidos", colors:["Uva", "Rojo", "Marfil", "Blanco", "Negro", "Azul cielo", "Beige", "Cafe", "Rosado", "Verde"], price:50000, img:"productos/044.jpg"},
  {id:45, name:"Vestido Animal Print", category:"Vestidos", colors:[], price:60000, img:"productos/045.jpg"},
  {id:46, name:"Jean Ancho Básico", category:"Pantalones y Jeans", colors:["Negro", "Azul"], price:85000, img:"productos/046.jpg"},
  {id:47, name:"Jean Pedrería", category:"Pantalones y Jeans", colors:[], price:110000, img:"productos/047.jpg"},
  {id:48, name:"Jean Ancho Rasgado", category:"Pantalones y Jeans", colors:[], price:100000, img:"productos/048.jpg"},
  {id:49, name:"Vestido Paris", category:"Vestidos", colors:["Camel", "Negro", "Azul cielo", "Lila", "Rojo", "Blanco"], price:50000, img:"productos/049.jpg"},
  {id:50, name:"Vestido Malla", category:"Vestidos", colors:["Rojo", "Blanco", "Negro"], price:60000, img:"productos/050.jpg"},
  {id:51, name:"Vestido Campesina", category:"Vestidos", colors:["Rojo", "Azul cielo", "Lila", "Beige", "Blanco", "Negro"], price:50000, img:"productos/051.jpg"},
  {id:52, name:"Corset Corazón", category:"Bodies y Corsets", colors:["Beige", "Rojo", "Negro"], price:40000, img:"productos/052.jpg"},
  {id:53, name:"Crop Mariposa", category:"Blusas y Tops", colors:["Blanco", "Rojo", "Negra"], price:45000, img:"productos/053.jpg"},
  {id:54, name:"Body Melissa", category:"Bodies y Corsets", colors:["Beige", "Azul oscuro", "Rojo", "Blanco", "Vinotinto"], price:45000, img:"productos/054.jpg"},
  {id:55, name:"Body Encaje", category:"Bodies y Corsets", colors:["Blanco"], price:45000, img:"productos/055.jpg"},
  {id:56, name:"Camisa Oversize Líneas", category:"Camisetas y Camisas", colors:["Verde", "Negro", "Blanco", "Azul", "Rojo"], price:60000, img:"productos/056.jpg"},
  {id:57, name:"Blusa Tela Galleta", category:"Blusas y Tops", colors:["Blanco", "Negro"], price:28000, img:"productos/057.jpg"},
  {id:58, name:"Body W Liciado", category:"Bodies y Corsets", colors:["Rojo", "Negro", "Beige", "Blanco", "Azul oscuro"], price:45000, img:"productos/058.jpg"},
  {id:59, name:"Short Biker", category:"Shorts", colors:["Rojo", "Azul", "Gris", "Negro", "Lila", "Rosado", "Morado", "Verde"], price:30000, img:"productos/059.jpg"},
  {id:60, name:"Camisa Licrada Nacional", category:"Camisetas y Camisas", colors:["Gris", "Verde", "Negra", "Azul"], price:35000, img:"productos/060.jpg"},
  {id:61, name:"Camisa Sport Importada", category:"Camisetas y Camisas", colors:["Blanca", "Azul", "Roja", "Negra", "Verde", "Gris"], price:45000, img:"productos/061.jpg"},
  {id:62, name:"Enterizo Adidas", category:"Conjuntos y Enteriozos", colors:["Beige"], price:65000, img:"productos/062.jpg"},
  {id:63, name:"Sudadera Oversize Hombre", category:"Buzos y Sudaderas", colors:["Morada", "Verde", "Rojo", "Negra", "Blanca"], price:60000, img:"productos/063.jpg"},
  {id:64, name:"Body Escote Espalda", category:"Bodies y Corsets", colors:["Azul", "Amarillo", "Negro", "Blanco", "Vinotinto", "Rosado"], price:60000, img:"productos/064.jpg"},
  {id:65, name:"Blusa Triángulo", category:"Blusas y Tops", colors:["Negra", "Blanca", "Azul cielo", "Amarilla", "Rosado"], price:60000, img:"productos/065.jpg"},
  {id:66, name:"Blusa Elegante", category:"Blusas y Tops", colors:["Amarillo", "Negro", "Blanco", "Azul cielo", "Rosado", "Vinotinto"], price:40000, img:"productos/066.jpg"},
  {id:67, name:"Body Elegante", category:"Bodies y Corsets", colors:["Rojo", "Negro", "Beige"], price:60000, img:"productos/067.jpg"},
  {id:68, name:"Camisa Oversize Galleta", category:"Camisetas y Camisas", colors:["Negro", "Marfil", "Beige"], price:55000, img:"productos/068.jpg"},
  {id:69, name:"Falda Short Cuero", category:"Shorts", colors:["Vinotinto", "Café", "Negro", "Beige"], price:50000, img:"productos/069.jpg"},
  {id:70, name:"Falda Cuero", category:"Faldas", colors:["Cafe", "Negro", "Vinotinto", "Beige"], price:45000, img:"productos/070.jpg"},
  {id:71, name:"Falda Cuero Larga", category:"Faldas", colors:["Negro", "Beige", "Vinotinto", "Cafe"], price:55000, img:"productos/071.jpg"},
  {id:72, name:"Enterizo con Copas Acanalado", category:"Conjuntos y Enteriozos", colors:["Azul Cielo"], price:90000, img:"productos/072.jpg"},
  {id:73, name:"Chaqueta Corta Deportiva", category:"Chaquetas", colors:["Roja", "Lila", "Gris", "Negra"], price:40000, img:"productos/073.jpg"},
  {id:74, name:"Vestido Straple", category:"Vestidos", colors:["Negro", "Rojo", "Camel", "Azul"], price:50000, img:"productos/074.jpg"},
  {id:75, name:"Vestido Prenses", category:"Vestidos", colors:["Azul cielo", "Negro", "Cafe"], price:50000, img:"productos/075.jpg"},
  {id:76, name:"Body Straple", category:"Bodies y Corsets", colors:["Amarillo", "Gris", "Negro"], price:40000, img:"productos/076.jpg"},
  {id:77, name:"Blusa Elegante Malla", category:"Blusas y Tops", colors:["Negra", "Azul Cielo"], price:35000, img:"productos/077.jpg"},
  {id:78, name:"Conjunto Polo", category:"Conjuntos y Enteriozos", colors:["Negro", "Camel", "Rojo", "Azul cielo", "Blanco", "Rosado"], price:70000, img:"productos/078.jpg"},
  {id:79, name:"Vestido Bandeja Abertura", category:"Vestidos", colors:["Verde manzana", "Rojo", "Negro"], price:50000, img:"productos/079.jpg"},
  {id:80, name:"Blusa Bandeja Larga", category:"Blusas y Tops", colors:["Negro"], price:50000, img:"productos/080.jpg"},
  {id:81, name:"Esqueleto Malla", category:"Bodies y Corsets", colors:["Azul cielo", "Rosado", "Amarillo", "Vinotinto"], price:40000, img:"productos/081.jpg"},
  {id:82, name:"Falda de Dril Prenses", category:"Faldas", colors:["Negro", "Beige", "Azul cielo"], price:45000, img:"productos/082.jpg"},
  {id:83, name:"Blusa Bandeja corta", category:"Buzos y Sudaderas", colors:["Negro", "Vinotinto"], price:40000, img:"productos/083.jpg"},
  {id:84, name:"Pantalón Algodón", category:"Pantalones y Jeans", colors:["Gris claro", "Negro", "Rojo", "Cafe"], price:45000, img:"productos/084.jpg"},
  {id:85, name:"Pantalón Pana", category:"Pantalones y Jeans", colors:["Rosado", "Negro", "Marfil"], price:45000, img:"productos/085.jpg"},
  {id:86, name:"Pantalón Polo dama", category:"Pantalones y Jeans", colors:["Cafe"], price:40000, img:"productos/086.jpg"},
  {id:87, name:"Pantalón Hombre Joger", category:"Pantalones y Jeans", colors:["Negro", "Gris", "Gris raton"], price:40000, img:"productos/087.jpg"},
  {id:88, name:"Licra Push-up", category:"Licras", colors:["Gris", "Azul oscuro", "Verde", "Morada"], price:45000, img:"productos/088.jpg"},
  {id:89, name:"Short Push-up Manchas", category:"Shorts", colors:["Azul cielo", "Rojo", "Negro", "Morado"], price:38000, img:"productos/089.jpg"},
  {id:90, name:"Conjunto Deportivo 2 Piezas", category:"Conjuntos y Enteriozos", colors:["Verde", "Negro"], price:100000, img:"productos/090.jpg"},
  {id:91, name:"Enterizo Corto Apertura Espalda", category:"Conjuntos y Enteriozos", colors:["Vinotinto", "Oscuro", "Verde"], price:65000, img:"productos/091.jpg"},
  {id:92, name:"Camiseta Polo", category:"Camisetas y Camisas", colors:["Azul cielo", "Azul oscuro", "Oscuro"], price:45000, img:"productos/092.jpg"},
  {id:93, name:"Camiseta Polo Línea", category:"Camisetas y Camisas", colors:["Rojo", "Azul oscuro"], price:50000, img:"productos/093.jpg"},
  {id:94, name:"Gorras Planas Beisboleras", category:"Accesorios", colors:[], price:55000, img:"productos/094.jpg"},
  {id:95, name:"Gorras Planas Beisboleras Cerradas", category:"Accesorios", colors:[], price:60000, img:"productos/095.jpg"},
  {id:96, name:"Gorras Planas Multimarca", category:"Accesorios", colors:[], price:50000, img:"productos/096.jpg"},
  {id:97, name:"Gorras Curvas Beisboleras", category:"Accesorios", colors:[], price:50000, img:"productos/097.jpg"},
  {id:98, name:"Gorras Multimarca 1.1", category:"Accesorios", colors:[], price:50000, img:"productos/098.jpg"},
  {id:99, name:"Gorras Multimarca", category:"Accesorios", colors:[], price:45000, img:"productos/099.jpg"},
];

const CATEGORIES = [...new Set(PRODUCTS.map(p => p.category))].sort();

